version: "3.8"
services:
  express: 
    build: ./backend # context
    container_name: myapp_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
  react:
    build:
      context: ./app
      target: development # stage in Dockerfile
    container_name: myapp_app
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/src
      - /app/node_modules
    # For interactive shell in react
    stdin_open: true
    tty: true